### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'model_variant'

### ISSUE THREAD

**Issue by Threekiii** [malllabiisc/CaRE#4]
Traceback (most recent call last):
  File "CaRe_main.py", line 211, in <module>
    main(args)
  File "CaRe_main.py", line 86, in main
    data = load_data(args)
  File "/root/CaRE/CaRe(B=TransE)/data.py", line 10, in __init__
    self.fetch_data()
  File "/root/CaRE/CaRe(B=TransE)/data.py", line 126, in fetch_data
    self.get_edges(self.canon_clusts)
  File "/root/CaRE/CaRe(B=TransE)/data.py", line 105, in get_edges
    if self.args.model_variant=='CaRe' and len(ent_clusts[ent])==1:
AttributeError: 'Namespace' object has no attribute 'model_variant'

**Comment by anindyasdas** [comment]
It seemed type error to me! there is no argument as model_variant!
I did the following:
```
#if self.args.model_variant=='CaRe' and len(ent_clusts[ent])==1:
if len(ent_clusts[ent])==1:
```
