### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by Threekiii** [malllabiisc/CaRE#5]
Traceback (most recent call last):
  File "CaRe_main.py", line 211, in <module>
    main(args)
  File "CaRe_main.py", line 86, in main
    data = load_data(args)
  File "/root/CaRE/CaRe(B=TransE)/data.py", line 10, in __init__
    self.fetch_data()
  File "/root/CaRE/CaRe(B=TransE)/data.py", line 130, in fetch_data
    self.entid2clustid)
ValueError: too many values to unpack (expected 3)

**Comment by anindyasdas** [comment]
The code has multiple errors, typos, for TransE algorithm self.get_train_triples only returns one argument. Hence this error!

Solution:
Comment out
#self.train_trips,self.rel2id,self.label_graph = self.get_train_triples(self.data_files["train_trip_path"],
                                                                               self.entid2clustid)

self.train_trips= self.get_train_triples(self.data_files["train_trip_path"], self.entid2clustid)
